version: 2
updates:
  - package-ecosystem: 'npm'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    directory: '/'
    groups:
      '@code-like-a-carpenter':
        patterns:
          - '*@code-like-a-carpenter*'
      '@opentelemetry':
        patterns:
          - '*@opentelemetry*'
      babel:
        patterns:
          - '*babel*'
      jest:
        patterns:
          - '*jest*'
      graphql:
        patterns:
          - '*graphql*'
      linters:
        patterns:
          - '*eslint*'
          - '*prettier*'
          - '*typescript*'
      remix:
        patterns:
          - '*remix*'
      sentry:
        patterns:
          - '*sentry*'
      storybook:
        patterns:
          - '*storybook*'
    ignore:
      # Ignore Node major version updates until we're ready to actually update
      # Node.
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
      # Pin AWS SDK to the version included in the Lambda Node 18 Runtime.
      - dependency-name: '@aws-sdk/*'
    schedule:
      interval: 'daily'
    versioning-strategy: 'increase'

  - package-ecosystem: 'github-actions'
    commit-message:
      prefix: 'ci'
      include: 'scope'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: 'daily'
