name: 'Setup'
description: 'Common setup steps for all jobs'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - uses: nrwl/nx-set-shas@v4
    - run: npm ci
      shell: bash
    - run: make
      shell: bash
