env:
  # Most of the code here will not be for the browser; use overrides to indicate
  # browser code.
  browser: false
  node: true

extends:
  - 'plugin:workspaces/recommended'
  - 'plugin:@ianwremmel/ianwremmel/modern'
  - 'plugin:@ianwremmel/ianwremmel/typescript'
  - 'prettier'

ignorePatterns:
  - dist

overrides:
  - files:
      - '**/*.ts'
      - '**/*.tsx'
    parserOptions:
      sourceType: module
    rules:
      # These rules do the wrong thing when they encounter type imports
      no-duplicate-imports: off
      import/no-duplicates: error

  - files:
      - '**/*.spec.*'
      - 'test/jest/spec/**/*'
      - '**/__mocks__/**/*'
    env:
      jest: true

parserOptions:
  sourceType: 'script'

plugins:
  - workspaces

settings:
  react:
    version: 'detect'
  import/internal-regex: '^@code-like-a-carpenter/'

rules:
  '@typescript-eslint/consistent-type-imports': 'error'
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - args: 'after-used'
      ignoreRestSiblings: true
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '!src/**/*'
        - '!packages/**/*'
  no-restricted-imports:
    - error
    - patterns:
        # Avoid importing directly from files in packages and instead allow only
        # importing from the main entry point.
        - 'src'
  workspaces/no-relative-imports: 'error'
  require-jsdoc: off
