env:
  # Most of the code here will not be for the browser; use overrides to indicate
  # browser code.
  browser: false
  node: true

extends:
  - 'plugin:workspaces/recommended'
  - 'plugin:@ianwremmel/ianwremmel/modern'
  - 'plugin:@ianwremmel/ianwremmel/typescript'
  - 'plugin:lodash/recommended'
  - 'prettier'

ignorePatterns:
  - dist
  - '!.graphqlrc.js'

overrides:
  - files:
      - '**/*.mjs'
      - '**/*.mts'
    parserOptions:
      sourceType: 'module'

  - files:
      - '**/*.graphql'
      - '**/*.graphqls'
    extends: 'plugin:@graphql-eslint/schema-recommended'
    rules:
      # Since we're building a bunch of different schema, not all of the shared
      # schema will be used in each combined schema ,so this rule can't be
      # usefully enforced.
      '@graphql-eslint/no-unreachable-types': off
      '@graphql-eslint/no-typename-prefix': off
      strict: off

  - files:
      - '**/*.mts'
      - '**/*.ts'
      - '**/*.tsx'
    parserOptions:
      sourceType: module
    rules:
      # These rules do the wrong thing when they encounter type imports
      no-duplicate-imports: off
      import/no-duplicates: error

  - files:
      - '**/*.spec.*'
      - '**/*.test.*'
      - 'test/jest/spec/**/*'
      - '**/__mocks__/**/*'
    env:
      jest: true

  - files:
      - '**/__generated__/**'
      - '**/*.generated.*'
    rules:
      '@typescript-eslint/no-explicit-any': off
      '@typescript-eslint/no-unused-vars': off
      complexity: off
      eslint-comments/disable-enable-pair: off
      eslint-comments/no-unlimited-disable: off
      no-restricted-imports: off
      prefer-destructuring: off
      sort-keys: off

  - files:
      - '*.d.mts'
      - '*.d.ts'
      - '*.d.json.ts'
    rules:
      eslint-comments/disable-enable-pair: off
      eslint-comments/no-unlimited-disable: off

parserOptions:
  ecmaVersion: 2022
  sourceType: 'script'

plugins:
  - workspaces

settings:
  import/internal-regex: '^@code-like-a-carpenter/'
  lodash:
    pragma: '_'
  react:
    version: 'detect'

rules:
  '@typescript-eslint/consistent-type-imports': 'error'
  '@typescript-eslint/no-explicit-any': 'warn'
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - args: 'after-used'
      ignoreRestSiblings: true
  import/extensions:
    - error
    - ignorePackages
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '!src/**/*'
        - '!packages/**/*'
  no-restricted-imports:
    - error
    - patterns:
        # Avoid importing directly from files in packages and instead allow only
        # importing from the main entry point.
        - 'src'
  workspaces/no-relative-imports: 'error'
  require-jsdoc: off

  'lodash/import-scope':
    - error
    - method-package
  'lodash/prefer-constant': off
  'lodash/prefer-get': off
  'lodash/prefer-includes': off
  'lodash/prefer-is-nil': off
  'lodash/prefer-lodash-chain': off
  'lodash/prefer-lodash-method': off
  'lodash/prefer-lodash-typecheck': off
  'lodash/prefer-matches': off
  'lodash/prefer-noop': off
  'lodash/prefer-over-quantifier': off
  'lodash/prefer-some': off
  'lodash/prefer-startswith': off
  'lodash/prefer-times': off
