AWSTemplateFormatVersion: '2010-09-09'
Conditions: {}
Globals:
  Function:
    Environment:
      Variables: {}
Outputs:
  FunctionName:
    Export:
      Name:
        Fn::Sub: '${AWS::StackName}-FunctionName'
    Value:
      Ref: 'Function'
  LogGroupName:
    Export:
      Name:
        Fn::Sub: '${AWS::StackName}-LogGroupName'
    Value:
      Ref: 'FunctionLogGroup'
Parameters:
  BatchSize:
    Type: 'Number'
  CodeUri:
    Type: 'String'
  EnvironmentVariables:
    Default: ''
    Type: 'String'
  EventBus:
    Type: 'String'
  LogRetentionInDays:
    Default: '3'
    Description: 'Log retention in days'
    Type: 'Number'
  MaximumRetryAttempts:
    Type: 'Number'
  MemorySize:
    Type: 'Number'
  StreamArn:
    Type: 'String'
  TableNames:
    Type: 'String'
  Timeout:
    Type: 'Number'
Resources:
  Function:
    Metadata:
      BuildMethod: 'esbuild'
      buildProperties:
        EntryPoints:
          - './index'
        External:
          - '@aws-sdk/*'
        Minify: false
        Sourcemap: true
        Target: 'es2022'
    Properties:
      CodeUri:
        Ref: 'CodeUri'
      Events:
        Stream:
          Properties:
            BatchSize:
              Ref: 'BatchSize'
            FunctionResponseTypes:
              - 'ReportBatchItemFailures'
            MaximumRetryAttempts:
              Ref: 'MaximumRetryAttempts'
            StartingPosition: 'TRIM_HORIZON'
            Stream:
              Ref: 'StreamArn'
          Type: 'DynamoDB'
      Handler: 'index.handler'
      MemorySize:
        Ref: 'MemorySize'
      Policies:
        - 'AWSLambdaBasicExecutionRole'
        - 'AWSLambda_ReadOnlyAccess'
        - 'AWSXrayWriteOnlyAccess'
        - 'CloudWatchLambdaInsightsExecutionRolePolicy'
        - CloudWatchPutMetricPolicy: {}
        - EventBridgePutEventsPolicy:
            EventBusName:
              Ref: 'EventBus'
      Runtime: 'nodejs18.x'
      Timeout:
        Ref: 'Timeout'
      Tracing: 'Active'
    Type: 'AWS::Serverless::Function'
  FunctionLogGroup:
    Properties:
      LogGroupName:
        Fn::Sub: '/aws/lambda/${Function}'
      RetentionInDays:
        Ref: 'LogRetentionInDays'
    Type: 'AWS::Logs::LogGroup'
Transform: 'AWS::Serverless-2016-10-31'
