Conditions: {}
Globals:
  Function:
    Environment:
      Variables:
        TABLE_SUBSCRIPTION_EVENT:
          Ref: TableSubscriptionEvent
Outputs:
  TableAccount:
    Description: The name of the DynamoDB table for TableAccount
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-TableAccount
    Value:
      Ref: TableAccount
  TableMetric:
    Description: The name of the DynamoDB table for TableMetric
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-TableMetric
    Value:
      Ref: TableMetric
  TablePlanMetric:
    Description: The name of the DynamoDB table for TablePlanMetric
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-TablePlanMetric
    Value:
      Ref: TablePlanMetric
  TableSubscriptionEvent:
    Description: The name of the DynamoDB table for TableSubscriptionEvent
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-TableSubscriptionEvent
    Value:
      Ref: TableSubscriptionEvent
Parameters: {}
Resources:
  TableAccount:
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: gsi1
          KeySchema:
            - AttributeName: gsi1pk
              KeyType: HASH
            - AttributeName: gsi1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: StageName
          Value:
            Ref: StageName
        - Key: TableName
          Value: TableAccount
    Type: AWS::DynamoDB::Table
  TableMetric:
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: StageName
          Value:
            Ref: StageName
        - Key: TableName
          Value: TableMetric
    Type: AWS::DynamoDB::Table
  TablePlanMetric:
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: StageName
          Value:
            Ref: StageName
        - Key: TableName
          Value: TablePlanMetric
    Type: AWS::DynamoDB::Table
  TableSubscriptionEvent:
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: StageName
          Value:
            Ref: StageName
        - Key: TableName
          Value: TableSubscriptionEvent
    Type: AWS::DynamoDB::Table
