#!/usr/bin/env bash

set -euo pipefail

example=$1

node ./packages/@code-like-a-carpenter/nx-auto package --package-name="$example" --type="example" 1>&2
npm run eslint -- --fix "examples/${example}/__generated__/**/*.ts" 1>&2
