#!/usr/bin/env bash

set -euo pipefail


action="$1"
shift

case "$action" in
  deploy)
    action=redeploy
    ;;
  destroy)
    ;;
  *)
    echo "Unknown action: $action"
    exit 1
    ;;
esac

# This script accepts a list of tests names from Check Run Reporter, filters
# them down to just examples, and then deploys those stacks

projects=''

for testfile in "$@"; do
  if [[ ! "$testfile" =~ ^examples/ ]]; then
    echo "Skipping $testfile which does not appear to test an AWS stack"
    continue
  fi

  projectName=$(echo "$testfile" | awk -F/ '{print $2}')
  if [[ "$projects" != *"$projectName"* ]]; then
    projects="$projects $projectName"
  fi
done

deployed=''

for projectName in $projects; do
  echo "::notice title=Deployment Status::${action^}ing $projectName for $testfile"
  ./scripts/sam "$action" aws "$projectName"
  echo "::notice title=Deployment Status::${action^}ed $projectName for $testfile"

  deployed="$deployed $testfile"
done

if [ -z "$deployed" ]; then
  echo "::error title=CI Misconfiguration::No stacks deployed"
  exit 1
fi

echo "deployed=$deployed" >> "$GITHUB_OUTPUT"
