#!/usr/bin/env bash

set -euo pipefail


action="$1"
shift

case "$action" in
  deploy)
    action=redeploy
    ;;
  destroy)
    ;;
  *)
    echo "Unknown action: $action"
    exit 1
    ;;
esac

# This script accepts a list of tests names from Check Run Reporter, filters
# them down to just examples, and then deploys those stacks

CMD="npx --no-install @code-like-a-carpenter/cli stack:list --as-projects"

for testfile in "$@"; do
  CMD="$CMD --test $testfile"
done

projects=$($CMD)

deployed=''

for projectName in $projects; do
  echo "::notice title=Deployment Status::${action^}ing $projectName for $testfile"
  ./scripts/sam "$action" aws "$projectName"
  echo "::notice title=Deployment Status::${action^}ed $projectName for $testfile"

  deployed="$deployed $testfile"
done

if [ -z "$deployed" ]; then
  echo "::error title=CI Misconfiguration::No stacks deployed"
  exit 1
fi

echo "deployed=$deployed" >> "$GITHUB_OUTPUT"
