#!/usr/bin/env bash

set -euo pipefail

PROJECT_ROOT=$1
EXTENSION=${2:-}

for f in $(find $PROJECT_ROOT/dist/types -type f); do
  outfile=$(echo $f | sed -e 's#/types/#/cjs-types/#' | sed -e 's#.d.mts#.d.ts#')
  mkdir -p "$(dirname "$outfile")"
  sed -e "s#.mjs#${EXTENSION}#g" "$f" | sed -e "s#.mts#${EXTENSION}#g" > "$outfile"
done
