#!/usr/bin/env bash
. "$(dirname -- "$0")/_/husky.sh"

# Lint staged files
npx --no-install lint-staged

# Make sure the readme TOC is up to date
if ! git diff --exit-code README.md; then
  echo 'README.md has unstaged changes. Please stage or stash them before committing'
  exit 1
fi

# At this point, we know there are no unstaged README changes, so only
# regenerate the toc if there are staged changes.
if ! git diff --staged --exit-code README.md; then
  make README.md
  git add README.md
fi

# Don't run in CI since it sem-rel may make non-conformant commits (that never
# get pushed)
if [ -z ${CI+x} ]; then
  # Autofix files that nx can autofix
  if ! npx nx format:check; then
    echo 'nx format:check has detected files that will fail CI checks'
    echo 'Please run `npx nx format:write` to fix them'
    echo 'Ideally, this pre-commit hook could determine which files they are, but '
    echo 'nx format only indicates there are failing files, not which ones.'

    exit 1
  fi
fi
